/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/owner/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Owner
         * @description Owner login
         *
         *     Returns JWT tokens for authenticated owner.
         *     If the owner has a temporary password, returns a restricted token
         *     that only works with set-password.
         */
        post: operations["login_owner_api_v1_owner_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Owner
         * @description Get current owner profile
         *
         *     Requires authentication via JWT token.
         */
        get: operations["get_current_owner_api_v1_owner_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Reset owner password (authenticated owner who knows their current password).
         *
         *     Requires old password for verification.
         */
        post: operations["reset_password_api_v1_owner_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Request a password reset email for owner.
         *
         *     Always returns 200 to prevent email enumeration.
         */
        post: operations["forgot_password_api_v1_owner_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/auth/set-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Password
         * @description Set new owner password using a temporary token.
         *
         *     Works for both flows:
         *     - First login: token from login response (purpose=set_password)
         *     - Forgot password: token from reset email (purpose=owner_password_reset)
         *
         *     Returns full access/refresh credentials on success.
         */
        post: operations["set_password_api_v1_owner_auth_set_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Companies
         * @description List all companies owned by the current owner
         *
         *     Returns a list of all companies with basic information.
         */
        get: operations["list_companies_api_v1_owner_companies_get"];
        put?: never;
        /**
         * Create Company
         * @description Create a new company
         *
         *     Only owners can create companies. The owner selects the telephony provider
         *     (Sipuni or Binotel) and provides the provider configuration.
         *
         *     The provider cannot be changed after company creation.
         */
        post: operations["create_company_api_v1_owner_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/companies/{company_id}/invite-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite Admin
         * @description Invite a superadmin to a company (Owner only)
         *
         *     Creates a COMPANY_ADMIN user with full admin permissions
         *     and sends an email invitation with a temporary password.
         */
        post: operations["invite_admin_api_v1_owner_companies__company_id__invite_admin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Company
         * @description Get detailed information about a specific company
         *
         *     Includes provider configuration and settings.
         */
        get: operations["get_company_api_v1_owner_companies__company_id__get"];
        /**
         * Update Company
         * @description Update company information
         *
         *     Can update name, settings, and active status.
         *     Provider type and configuration cannot be changed.
         */
        put: operations["update_company_api_v1_owner_companies__company_id__put"];
        post?: never;
        /**
         * Delete Company
         * @description Delete a company
         *
         *     By default performs soft delete (can be restored).
         *     Use hard=true for permanent deletion.
         */
        delete: operations["delete_company_api_v1_owner_companies__company_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/companies/{company_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Company
         * @description Activate a suspended company
         */
        post: operations["activate_company_api_v1_owner_companies__company_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/companies/{company_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate Company
         * @description Deactivate a company (suspend access)
         */
        post: operations["deactivate_company_api_v1_owner_companies__company_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Contracts
         * @description List all contracts owned by the current owner, with optional filters.
         */
        get: operations["list_contracts_api_v1_owner_contracts_get"];
        put?: never;
        /**
         * Create Contract
         * @description Create a contract for a company.
         *
         *     Validates company ownership and ensures no duplicate active contracts.
         */
        post: operations["create_contract_api_v1_owner_contracts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Contract
         * @description Get detailed contract information with current usage counts.
         */
        get: operations["get_contract_api_v1_owner_contracts__contract_id__get"];
        /**
         * Update Contract
         * @description Update contract limits, pricing, or payment status.
         */
        put: operations["update_contract_api_v1_owner_contracts__contract_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/contracts/{contract_id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renew Contract
         * @description Renew a contract: reset status to ACTIVE and extend end_date.
         */
        post: operations["renew_contract_api_v1_owner_contracts__contract_id__renew_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/contracts/{contract_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Contract
         * @description Cancel a contract.
         */
        post: operations["cancel_contract_api_v1_owner_contracts__contract_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/analytics/platform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Platform Analytics
         * @description Get platform-wide analytics (Owner only)
         *
         *     OPTIMIZED:
         *     - Single query for company/user counts
         *     - Aggregated stats across all companies (not N queries)
         *     - Top companies ranked in single query
         */
        get: operations["get_platform_analytics_api_v1_owner_analytics_platform_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/analytics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Owner Dashboard
         * @description Get owner dashboard (Owner only)
         *
         *     OPTIMIZED:
         *     - Caching with 5 minute TTL
         *     - Aggregated queries across all companies
         *     - Single queries for trends
         */
        get: operations["get_owner_dashboard_api_v1_owner_analytics_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/analytics/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Owner Cache
         * @description Clear owner analytics cache
         *
         *     Use this after bulk data imports or when you need fresh data.
         */
        delete: operations["clear_owner_cache_api_v1_owner_analytics_cache_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/owner/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Permissions
         * @description List all available permissions and default permissions per role
         *
         *     Returns every permission constant and the default set for each company role.
         */
        get: operations["list_permissions_api_v1_owner_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminDashboard
         * @description Admin dashboard data
         */
        AdminDashboard: {
            today: components["schemas"]["TeamAnalytics"];
            this_week: components["schemas"]["TeamAnalytics"];
            this_month: components["schemas"]["TeamAnalytics"];
            this_year: components["schemas"]["TeamAnalytics"];
            conversion_funnel: components["schemas"]["ConversionFunnel"];
            pipeline_health: components["schemas"]["PipelineHealth"];
            /**
             * Peak Call Hours
             * @default []
             */
            peak_call_hours: {
                [key: string]: unknown;
            }[];
            /**
             * Calls Trend
             * @default []
             */
            calls_trend: {
                [key: string]: unknown;
            }[];
            /**
             * Revenue Trend
             * @default []
             */
            revenue_trend: {
                [key: string]: unknown;
            }[];
        };
        /** AuthorizedResponse */
        AuthorizedResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email */
            email: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Must Change Password
             * @default false
             */
            must_change_password: boolean;
            credentials: components["schemas"]["BearerToken"];
        };
        /** BearerToken */
        BearerToken: {
            /**
             * Type
             * @default Bearer
             */
            type: string;
            /** Access */
            access: string;
            /** Refresh */
            refresh: string;
        };
        /**
         * BillingPeriodEnum
         * @description Billing period enumeration
         * @enum {string}
         */
        BillingPeriodEnum: "monthly" | "yearly";
        /**
         * CallDirectionEnum
         * @description Call direction enumeration
         * @enum {string}
         */
        CallDirectionEnum: "inbound" | "outbound" | "internal";
        /**
         * CallEventResponse
         * @description Call event response
         */
        CallEventResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Id */
            id: number;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            provider_type: components["schemas"]["ProviderEnum"];
            /** Phone 1 */
            phone_1?: string | null;
            /** Phone 2 */
            phone_2?: string | null;
            /** Operator Id */
            operator_id?: string | null;
            direction?: components["schemas"]["CallDirectionEnum"] | null;
            state?: components["schemas"]["CallStatusEnum"] | null;
            /** Attempts */
            attempts: number;
            /** Waiting Sec */
            waiting_sec?: number | null;
            /** Billing Sec */
            billing_sec?: number | null;
            /** Call Start Timestamp */
            call_start_timestamp?: number | null;
            /** Call End Timestamp */
            call_end_timestamp?: number | null;
            /** Contact Id */
            contact_id?: string | null;
            /** Lead Id */
            lead_id?: string | null;
            /** Has Recording */
            readonly has_recording: boolean;
        };
        /**
         * CallLinkRequest
         * @description Link call to CRM entities
         */
        CallLinkRequest: {
            /** Contact Id */
            contact_id?: string | null;
            /** Lead Id */
            lead_id?: string | null;
            /** Deal Id */
            deal_id?: string | null;
        };
        /**
         * CallNumberRequest
         * @description Request to call from internal SIP extension to external phone
         */
        CallNumberRequest: {
            /**
             * Phone
             * @description External phone number to call
             */
            phone: string;
            /**
             * Operator Id
             * @description Operator identifier: UUID, phone, email, or SIP number
             */
            operator_id: string;
            /**
             * Reverse
             * @description Call order: False = internal first, True = external first
             * @default false
             */
            reverse: boolean;
            /**
             * Antiaon
             * @description Hide caller ID
             * @default false
             */
            antiaon: boolean;
            /**
             * Order Id
             * @description External order/ticket ID
             */
            order_id?: string | null;
            /** Utm Source */
            utm_source?: string | null;
            /** Utm Medium */
            utm_medium?: string | null;
            /** Utm Campaign */
            utm_campaign?: string | null;
        };
        /**
         * CallOutcomeUpdate
         * @description Update call outcome
         */
        CallOutcomeUpdate: {
            /**
             * Outcome
             * @description Call outcome
             */
            outcome: string;
            /**
             * Disposition Notes
             * @description Notes about the call
             */
            disposition_notes?: string | null;
        };
        /**
         * CallRequest
         * @description Request to call from external number to external number
         */
        CallRequest: {
            /**
             * Phone 1
             * @description First phone number (caller)
             */
            phone_1: string;
            /**
             * Phone 2
             * @description Second phone number (receiver)
             */
            phone_2: string;
            /**
             * Operator Id
             * @description Operator identifier: UUID, phone, email, or SIP number
             */
            operator_id?: string | null;
            /**
             * Order Id
             * @description External order/ticket ID
             */
            order_id?: string | null;
            /** Utm Source */
            utm_source?: string | null;
            /** Utm Medium */
            utm_medium?: string | null;
            /** Utm Campaign */
            utm_campaign?: string | null;
        };
        /**
         * CallResponse
         * @description Response from call initiation
         */
        CallResponse: {
            /** Success */
            success: boolean;
            /**
             * Call Id
             * @description Company-scoped call number
             */
            call_id?: number | null;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * CallStats
         * @description Call statistics
         */
        CallStats: {
            /**
             * Total Calls
             * @default 0
             */
            total_calls: number;
            /**
             * Answered Calls
             * @default 0
             */
            answered_calls: number;
            /**
             * Missed Calls
             * @default 0
             */
            missed_calls: number;
            /**
             * Outbound Calls
             * @default 0
             */
            outbound_calls: number;
            /**
             * Inbound Calls
             * @default 0
             */
            inbound_calls: number;
            /**
             * Total Duration
             * @default 0
             */
            total_duration: number;
            /**
             * Average Duration
             * @default 0
             */
            average_duration: number;
            /**
             * Success Rate
             * @default 0
             */
            success_rate: number;
        };
        /**
         * CallStatusEnum
         * @description Call status enumeration
         * @enum {string}
         */
        CallStatusEnum: "ANSWER" | "BUSY" | "NOANSWER" | "CANCEL" | "CONGESTION" | "CHANUNAVAIL";
        /**
         * CallTreeRequest
         * @description Request to call external number through a call tree/scheme
         */
        CallTreeRequest: {
            /**
             * Phone
             * @description External phone number to call
             */
            phone: string;
            /**
             * Operator Id
             * @description Operator identifier: UUID, phone, email, or SIP number
             */
            operator_id: string;
            /**
             * Tree
             * @description Call tree/scheme identifier (e.g., '000-913898')
             */
            tree: string;
            /**
             * Reverse
             * @description Call order: False = external first, True = tree first
             * @default false
             */
            reverse: boolean;
            /**
             * Call Attempt Time
             * @description Attempt duration in seconds (min 30)
             * @default 30
             */
            call_attempt_time: number;
            /**
             * Order Id
             * @description External order/ticket ID
             */
            order_id?: string | null;
            /** Utm Source */
            utm_source?: string | null;
            /** Utm Medium */
            utm_medium?: string | null;
            /** Utm Campaign */
            utm_campaign?: string | null;
        };
        /**
         * CompanyCreateRequest
         * @description Create company request
         * @example {
         *       "name": "My Company LLC",
         *       "provider_config": {
         *         "cabinet_id": "12345",
         *         "security_key": "your-secret-key"
         *       },
         *       "provider_type": "sipuni",
         *       "settings": {
         *         "language": "ru",
         *         "timezone": "Asia/Tashkent"
         *       },
         *       "subdomain": "mycompany"
         *     }
         */
        CompanyCreateRequest: {
            /** Name */
            name: string;
            /**
             * Subdomain
             * @description Company subdomain (auto-generated if not provided)
             */
            subdomain?: string | null;
            /**
             * Provider Type
             * @description Provider: sipuni or binotel
             */
            provider_type: string;
            /**
             * Provider Config
             * @description Provider-specific configuration (requires cabinet_id and security_key)
             */
            provider_config: {
                [key: string]: unknown;
            };
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CompanyDetailResponse
         * @description Detailed company response with config
         */
        CompanyDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Subdomain */
            subdomain: string;
            /** Provider Type */
            provider_type: string;
            /** Is Active */
            is_active: boolean;
            /** Webhook Url */
            webhook_url?: string | null;
            /**
             * Users Count
             * @default 0
             */
            users_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Provider Config */
            provider_config: {
                [key: string]: unknown;
            };
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
            /** Webhook Token */
            webhook_token: string;
        };
        /**
         * CompanyPerformance
         * @description Individual company performance
         */
        CompanyPerformance: {
            /** Company Id */
            company_id: string;
            /** Company Name */
            company_name: string;
            /**
             * Total Users
             * @default 0
             */
            total_users: number;
            /**
             * Active Users
             * @default 0
             */
            active_users: number;
            /**
             * Total Calls
             * @default 0
             */
            total_calls: number;
            /**
             * Total Leads
             * @default 0
             */
            total_leads: number;
            /**
             * Total Deals
             * @default 0
             */
            total_deals: number;
            /**
             * Total Revenue
             * @default 0
             */
            total_revenue: number;
            /**
             * Growth Rate
             * @default 0
             */
            growth_rate: number;
        };
        /**
         * CompanyResponse
         * @description Company response
         */
        CompanyResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Subdomain */
            subdomain: string;
            /** Provider Type */
            provider_type: string;
            /** Is Active */
            is_active: boolean;
            /** Webhook Url */
            webhook_url?: string | null;
            /**
             * Users Count
             * @default 0
             */
            users_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CompanyUpdateRequest
         * @description Update company request
         */
        CompanyUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * ContactCreateRequest
         * @description Create contact request
         */
        ContactCreateRequest: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Position */
            position?: string | null;
            /** Source */
            source?: string | null;
            /** Custom Fields */
            custom_fields?: {
                [key: string]: unknown;
            } | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * ContactResponse
         * @description Contact response
         */
        ContactResponse: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Position */
            position?: string | null;
            /** Source */
            source?: string | null;
            /** Custom Fields */
            custom_fields?: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Created By */
            created_by: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Tags */
            tags?: string[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Total Leads
             * @default 0
             */
            total_leads: number;
            /**
             * Total Deals
             * @default 0
             */
            total_deals: number;
            /**
             * Total Calls
             * @default 0
             */
            total_calls: number;
        };
        /**
         * ContactUpdateRequest
         * @description Update contact request
         */
        ContactUpdateRequest: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Position */
            position?: string | null;
            /** Source */
            source?: string | null;
            /** Custom Fields */
            custom_fields?: {
                [key: string]: unknown;
            } | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * ContractCreateRequest
         * @description Create a new contract for a company
         * @example {
         *       "billing_period": "monthly",
         *       "company_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "currency": "USD",
         *       "end_date": "2025-12-31",
         *       "max_admins": 2,
         *       "max_managers": 5,
         *       "max_operators": 20,
         *       "max_storage_gb": 50,
         *       "name": "Standard Plan",
         *       "price": 99.99,
         *       "start_date": "2025-01-01"
         *     }
         */
        ContractCreateRequest: {
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Name */
            name: string;
            /**
             * Max Admins
             * @default 1
             */
            max_admins: number;
            /**
             * Max Managers
             * @default 5
             */
            max_managers: number;
            /**
             * Max Operators
             * @default 10
             */
            max_operators: number;
            /**
             * Max Storage Gb
             * @default 10
             */
            max_storage_gb: number;
            /** Price */
            price: number | string;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** @default monthly */
            billing_period: components["schemas"]["BillingPeriodEnum"];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Next Payment Date */
            next_payment_date?: string | null;
            /**
             * Grace Period Days
             * @default 30
             */
            grace_period_days: number;
            /**
             * Auto Renew
             * @default false
             */
            auto_renew: boolean;
            /** Notes */
            notes?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ContractDetailResponse
         * @description Detailed contract response with current usage counts
         */
        ContractDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Name */
            name: string;
            /** Max Admins */
            max_admins: number;
            /** Max Managers */
            max_managers: number;
            /** Max Operators */
            max_operators: number;
            /** Max Storage Gb */
            max_storage_gb: number;
            /** Price */
            price: string;
            /** Currency */
            currency: string;
            billing_period: components["schemas"]["BillingPeriodEnum"];
            status: components["schemas"]["ContractStatusEnum"];
            payment_status: components["schemas"]["PaymentStatusEnum"];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Next Payment Date */
            next_payment_date?: string | null;
            /** Grace Period Days */
            grace_period_days: number;
            /** Is Active */
            is_active: boolean;
            /** Auto Renew */
            auto_renew: boolean;
            /** Notes */
            notes?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Days Until Expiry */
            days_until_expiry?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Current Admins
             * @default 0
             */
            current_admins: number;
            /**
             * Current Managers
             * @default 0
             */
            current_managers: number;
            /**
             * Current Operators
             * @default 0
             */
            current_operators: number;
        };
        /**
         * ContractRenewRequest
         * @description Renew an existing contract
         */
        ContractRenewRequest: {
            /**
             * New End Date
             * Format: date
             */
            new_end_date: string;
            /** Next Payment Date */
            next_payment_date?: string | null;
            /** Price */
            price?: number | string | null;
        };
        /**
         * ContractResponse
         * @description Standard contract response
         */
        ContractResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Name */
            name: string;
            /** Max Admins */
            max_admins: number;
            /** Max Managers */
            max_managers: number;
            /** Max Operators */
            max_operators: number;
            /** Max Storage Gb */
            max_storage_gb: number;
            /** Price */
            price: string;
            /** Currency */
            currency: string;
            billing_period: components["schemas"]["BillingPeriodEnum"];
            status: components["schemas"]["ContractStatusEnum"];
            payment_status: components["schemas"]["PaymentStatusEnum"];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Next Payment Date */
            next_payment_date?: string | null;
            /** Grace Period Days */
            grace_period_days: number;
            /** Is Active */
            is_active: boolean;
            /** Auto Renew */
            auto_renew: boolean;
            /** Notes */
            notes?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Days Until Expiry */
            days_until_expiry?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ContractStatusEnum
         * @description Contract status enumeration
         * @enum {string}
         */
        ContractStatusEnum: "active" | "warning" | "grace_period" | "expired" | "suspended" | "cancelled";
        /**
         * ContractStatusResponse
         * @description Simplified contract view for company users
         */
        ContractStatusResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            status: components["schemas"]["ContractStatusEnum"];
            payment_status: components["schemas"]["PaymentStatusEnum"];
            /** Max Admins */
            max_admins: number;
            /** Max Managers */
            max_managers: number;
            /** Max Operators */
            max_operators: number;
            /** Max Storage Gb */
            max_storage_gb: number;
            /**
             * Current Admins
             * @default 0
             */
            current_admins: number;
            /**
             * Current Managers
             * @default 0
             */
            current_managers: number;
            /**
             * Current Operators
             * @default 0
             */
            current_operators: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Days Until Expiry */
            days_until_expiry?: number | null;
            billing_period: components["schemas"]["BillingPeriodEnum"];
            /** Auto Renew */
            auto_renew: boolean;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /**
         * ContractUpdateRequest
         * @description Update an existing contract
         */
        ContractUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Max Admins */
            max_admins?: number | null;
            /** Max Managers */
            max_managers?: number | null;
            /** Max Operators */
            max_operators?: number | null;
            /** Max Storage Gb */
            max_storage_gb?: number | null;
            /** Price */
            price?: number | string | null;
            /** Currency */
            currency?: string | null;
            billing_period?: components["schemas"]["BillingPeriodEnum"] | null;
            status?: components["schemas"]["ContractStatusEnum"] | null;
            payment_status?: components["schemas"]["PaymentStatusEnum"] | null;
            /** Next Payment Date */
            next_payment_date?: string | null;
            /** Grace Period Days */
            grace_period_days?: number | null;
            /** Auto Renew */
            auto_renew?: boolean | null;
            /** Notes */
            notes?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ConversionFunnel
         * @description Lead conversion funnel
         */
        ConversionFunnel: {
            /**
             * Total Leads
             * @default 0
             */
            total_leads: number;
            /**
             * Contacted
             * @default 0
             */
            contacted: number;
            /**
             * Qualified
             * @default 0
             */
            qualified: number;
            /**
             * Deals Created
             * @default 0
             */
            deals_created: number;
            /**
             * Deals Won
             * @default 0
             */
            deals_won: number;
            /**
             * Contact Rate
             * @default 0
             */
            contact_rate: number;
            /**
             * Qualification Rate
             * @default 0
             */
            qualification_rate: number;
            /**
             * Deal Rate
             * @default 0
             */
            deal_rate: number;
            /**
             * Win Rate
             * @default 0
             */
            win_rate: number;
            /**
             * Overall Conversion
             * @default 0
             */
            overall_conversion: number;
        };
        /**
         * DealCreateRequest
         * @description Create deal request
         */
        DealCreateRequest: {
            /** Title */
            title: string;
            /** Contact Id */
            contact_id?: string | null;
            /** Lead Id */
            lead_id?: string | null;
            /** Amount */
            amount: number;
            /**
             * Currency
             * @default USD
             */
            currency: string | null;
            /**
             * Probability
             * @default 0
             */
            probability: number | null;
            /** Expected Close Date */
            expected_close_date?: string | null;
            /** Description */
            description?: string | null;
            /** Custom Fields */
            custom_fields?: {
                [key: string]: unknown;
            } | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * DealResponse
         * @description Deal response
         */
        DealResponse: {
            /** Title */
            title: string;
            /** Contact Id */
            contact_id?: string | null;
            /** Lead Id */
            lead_id?: string | null;
            /** Amount */
            amount: number;
            /**
             * Currency
             * @default USD
             */
            currency: string | null;
            /**
             * Probability
             * @default 0
             */
            probability: number | null;
            /** Expected Close Date */
            expected_close_date?: string | null;
            /** Description */
            description?: string | null;
            /** Custom Fields */
            custom_fields?: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Stage */
            stage?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Closed Date */
            closed_date?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Contact Name */
            contact_name?: string | null;
            /** Assigned To Name */
            assigned_to_name?: string | null;
            /**
             * Weighted Value
             * @default 0
             */
            weighted_value: number;
        };
        /**
         * DealStats
         * @description Deal statistics
         */
        DealStats: {
            /**
             * Total Deals
             * @default 0
             */
            total_deals: number;
            /**
             * Prospecting
             * @default 0
             */
            prospecting: number;
            /**
             * Negotiation
             * @default 0
             */
            negotiation: number;
            /**
             * Won
             * @default 0
             */
            won: number;
            /**
             * Lost
             * @default 0
             */
            lost: number;
            /**
             * Total Value
             * @default 0
             */
            total_value: number;
            /**
             * Won Value
             * @default 0
             */
            won_value: number;
            /**
             * Average Deal Size
             * @default 0
             */
            average_deal_size: number;
            /**
             * Win Rate
             * @default 0
             */
            win_rate: number;
        };
        /**
         * DealUpdateRequest
         * @description Update deal request
         */
        DealUpdateRequest: {
            /** Title */
            title?: string | null;
            /** Contact Id */
            contact_id?: string | null;
            /** Lead Id */
            lead_id?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Amount */
            amount?: number | null;
            /** Currency */
            currency?: string | null;
            /** Probability */
            probability?: number | null;
            /** Expected Close Date */
            expected_close_date?: string | null;
            /** Description */
            description?: string | null;
            /** Custom Fields */
            custom_fields?: {
                [key: string]: unknown;
            } | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InviteAdminRequest
         * @description Owner invites a superadmin to a company (gets full admin permissions)
         */
        InviteAdminRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /**
         * LeadCreateRequest
         * @description Create lead request
         */
        LeadCreateRequest: {
            /** Title */
            title: string;
            /** Contact Id */
            contact_id?: string | null;
            /** Source */
            source?: string | null;
            /** Description */
            description?: string | null;
            /** Estimated Value */
            estimated_value?: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string | null;
            /** Custom Fields */
            custom_fields?: {
                [key: string]: unknown;
            } | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * LeadResponse
         * @description Lead response
         */
        LeadResponse: {
            /** Title */
            title: string;
            /** Contact Id */
            contact_id?: string | null;
            /** Source */
            source?: string | null;
            /** Description */
            description?: string | null;
            /** Estimated Value */
            estimated_value?: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string | null;
            /** Custom Fields */
            custom_fields?: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Status */
            status?: string | null;
            /** Pipeline Stage */
            pipeline_stage?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Tags */
            tags?: string[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Contact Name */
            contact_name?: string | null;
            /** Assigned To Name */
            assigned_to_name?: string | null;
        };
        /**
         * LeadStats
         * @description Lead statistics
         */
        LeadStats: {
            /**
             * Total Leads
             * @default 0
             */
            total_leads: number;
            /**
             * New Leads
             * @default 0
             */
            new_leads: number;
            /**
             * Contacted Leads
             * @default 0
             */
            contacted_leads: number;
            /**
             * Qualified Leads
             * @default 0
             */
            qualified_leads: number;
            /**
             * Converted Leads
             * @default 0
             */
            converted_leads: number;
            /**
             * Lost Leads
             * @default 0
             */
            lost_leads: number;
            /**
             * Conversion Rate
             * @default 0
             */
            conversion_rate: number;
        };
        /**
         * LeadUpdateRequest
         * @description Update lead request
         */
        LeadUpdateRequest: {
            /** Title */
            title?: string | null;
            /** Contact Id */
            contact_id?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Source */
            source?: string | null;
            /** Description */
            description?: string | null;
            /** Estimated Value */
            estimated_value?: number | null;
            /** Currency */
            currency?: string | null;
            /** Custom Fields */
            custom_fields?: {
                [key: string]: unknown;
            } | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * NoteCreateRequest
         * @description Create note request
         */
        NoteCreateRequest: {
            /** Content */
            content: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: string;
        };
        /**
         * NoteResponse
         * @description Note response
         */
        NoteResponse: {
            /** Content */
            content: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Created By */
            created_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Created By Name */
            created_by_name?: string | null;
        };
        /**
         * NoteUpdateRequest
         * @description Update note request
         */
        NoteUpdateRequest: {
            /** Content */
            content?: string | null;
        };
        /**
         * OperatorAnalytics
         * @description Operator personal analytics
         */
        OperatorAnalytics: {
            /**
             * Period
             * @description today, week, month, year
             */
            period: string;
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            calls: components["schemas"]["CallStats"];
            leads: components["schemas"]["LeadStats"];
            deals: components["schemas"]["DealStats"];
            tasks: components["schemas"]["TaskStats"];
            /**
             * Total Activities
             * @default 0
             */
            total_activities: number;
            /**
             * Productivity Score
             * @default 0
             */
            productivity_score: number;
        };
        /**
         * OperatorDashboard
         * @description Operator dashboard data
         */
        OperatorDashboard: {
            today: components["schemas"]["OperatorAnalytics"];
            this_week: components["schemas"]["OperatorAnalytics"];
            this_month: components["schemas"]["OperatorAnalytics"];
            /**
             * Upcoming Tasks
             * @default 0
             */
            upcoming_tasks: number;
            /**
             * Pending Leads
             * @default 0
             */
            pending_leads: number;
            /**
             * Active Deals
             * @default 0
             */
            active_deals: number;
            /**
             * Recent Calls
             * @default []
             */
            recent_calls: {
                [key: string]: unknown;
            }[];
            /**
             * Recent Tasks
             * @default []
             */
            recent_tasks: {
                [key: string]: unknown;
            }[];
        };
        /**
         * OperatorPerformance
         * @description Individual operator performance
         */
        OperatorPerformance: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            calls: components["schemas"]["CallStats"];
            leads: components["schemas"]["LeadStats"];
            deals: components["schemas"]["DealStats"];
            tasks: components["schemas"]["TaskStats"];
            /**
             * Productivity Score
             * @default 0
             */
            productivity_score: number;
        };
        /**
         * OwnerDashboard
         * @description Owner platform dashboard
         */
        OwnerDashboard: {
            today: components["schemas"]["PlatformAnalytics"];
            this_week: components["schemas"]["PlatformAnalytics"];
            this_month: components["schemas"]["PlatformAnalytics"];
            this_year: components["schemas"]["PlatformAnalytics"];
            /**
             * System Health
             * @default {}
             */
            system_health: {
                [key: string]: unknown;
            };
            /**
             * Growth Trend
             * @default []
             */
            growth_trend: {
                [key: string]: unknown;
            }[];
            /**
             * Churn Analysis
             * @default {}
             */
            churn_analysis: {
                [key: string]: unknown;
            };
        };
        /**
         * OwnerLoginRequest
         * @description Owner login request schema
         */
        OwnerLoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * OwnerResponse
         * @description Owner response
         */
        OwnerResponse: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Email Verified */
            email_verified: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * OwnerWithCredentials
         * @description Owner response with JWT credentials
         */
        OwnerWithCredentials: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Email Verified */
            email_verified: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Must Change Password
             * @default false
             */
            must_change_password: boolean;
            /** Credentials */
            credentials: {
                [key: string]: unknown;
            };
        };
        /**
         * PaginatedResponse
         * @description Paginated list response
         */
        PaginatedResponse: {
            /** Items */
            items: unknown[];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * PaymentStatusEnum
         * @description Payment status enumeration
         * @enum {string}
         */
        PaymentStatusEnum: "paid" | "pending" | "overdue" | "failed";
        /**
         * PermissionGroupCreateRequest
         * @description Create a custom permission group
         */
        PermissionGroupCreateRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Permissions
             * @description List of permission strings
             */
            permissions: string[];
        };
        /**
         * PermissionGroupListResponse
         * @description Permission group list response
         */
        PermissionGroupListResponse: {
            /** Groups */
            groups: components["schemas"]["PermissionGroupResponse"][];
            /** Total */
            total: number;
        };
        /**
         * PermissionGroupResponse
         * @description Permission group response
         */
        PermissionGroupResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Id */
            company_id?: string | null;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Permissions */
            permissions: string[];
            /** Is System */
            is_system: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PermissionGroupUpdateRequest
         * @description Update a permission group
         */
        PermissionGroupUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Permissions */
            permissions?: string[] | null;
        };
        /**
         * PipelineHealth
         * @description Sales pipeline health
         */
        PipelineHealth: {
            /**
             * Total Value
             * @default 0
             */
            total_value: number;
            /**
             * Weighted Value
             * @default 0
             */
            weighted_value: number;
            /**
             * By Stage
             * @default {}
             */
            by_stage: {
                [key: string]: unknown;
            };
            /**
             * Stuck Deals
             * @default 0
             */
            stuck_deals: number;
            /**
             * Forecast
             * @default 0
             */
            forecast: number;
        };
        /**
         * PlatformAnalytics
         * @description Platform-wide analytics (for owners)
         */
        PlatformAnalytics: {
            /** Period */
            period: string;
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /**
             * Total Companies
             * @default 0
             */
            total_companies: number;
            /**
             * Active Companies
             * @default 0
             */
            active_companies: number;
            /**
             * Total Users
             * @default 0
             */
            total_users: number;
            /**
             * Active Users
             * @default 0
             */
            active_users: number;
            /**
             * Total Calls
             * @default 0
             */
            total_calls: number;
            /**
             * Total Leads
             * @default 0
             */
            total_leads: number;
            /**
             * Total Deals
             * @default 0
             */
            total_deals: number;
            /**
             * Total Revenue
             * @default 0
             */
            total_revenue: number;
            /**
             * New Companies
             * @default 0
             */
            new_companies: number;
            /**
             * New Users
             * @default 0
             */
            new_users: number;
            /**
             * Revenue Growth
             * @default 0
             */
            revenue_growth: number;
            /**
             * Top Companies
             * @default []
             */
            top_companies: components["schemas"]["CompanyPerformance"][];
        };
        /**
         * ProfileUpdateRequest
         * @description Update own profile (non-admin fields only)
         */
        ProfileUpdateRequest: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Language */
            language?: string | null;
        };
        /**
         * ProviderEnum
         * @description Telephony provider enumeration
         * @enum {string}
         */
        ProviderEnum: "sipuni" | "binotel";
        /**
         * RefreshTokenRequest
         * @description Request body for token refresh
         */
        RefreshTokenRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** Old Password */
            old_password: string;
            /** New Password */
            new_password: string;
        };
        /** SetPasswordRequest */
        SetPasswordRequest: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /**
         * TaskCreateRequest
         * @description Create task request
         */
        TaskCreateRequest: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Entity Type */
            entity_type?: string | null;
            /** Entity Id */
            entity_id?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
        };
        /**
         * TaskResponse
         * @description Task response
         */
        TaskResponse: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Entity Type */
            entity_type?: string | null;
            /** Entity Id */
            entity_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Status */
            status?: string | null;
            /** Priority */
            priority?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Created By */
            created_by?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Assigned To Name */
            assigned_to_name?: string | null;
        };
        /**
         * TaskStats
         * @description Task statistics
         */
        TaskStats: {
            /**
             * Total Tasks
             * @default 0
             */
            total_tasks: number;
            /**
             * Pending Tasks
             * @default 0
             */
            pending_tasks: number;
            /**
             * Completed Tasks
             * @default 0
             */
            completed_tasks: number;
            /**
             * Overdue Tasks
             * @default 0
             */
            overdue_tasks: number;
            /**
             * Completion Rate
             * @default 0
             */
            completion_rate: number;
        };
        /**
         * TaskUpdateRequest
         * @description Update task request
         */
        TaskUpdateRequest: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Entity Type */
            entity_type?: string | null;
            /** Entity Id */
            entity_id?: string | null;
        };
        /**
         * TeamAnalytics
         * @description Team-wide analytics (for admins)
         */
        TeamAnalytics: {
            /** Period */
            period: string;
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /**
             * Total Operators
             * @default 0
             */
            total_operators: number;
            /**
             * Active Operators
             * @default 0
             */
            active_operators: number;
            calls: components["schemas"]["CallStats"];
            leads: components["schemas"]["LeadStats"];
            deals: components["schemas"]["DealStats"];
            tasks: components["schemas"]["TaskStats"];
            /**
             * Total Revenue
             * @default 0
             */
            total_revenue: number;
            /**
             * Revenue Growth
             * @default 0
             */
            revenue_growth: number;
            /**
             * Top Operators By Calls
             * @default []
             */
            top_operators_by_calls: components["schemas"]["OperatorPerformance"][];
            /**
             * Top Operators By Deals
             * @default []
             */
            top_operators_by_deals: components["schemas"]["OperatorPerformance"][];
            /**
             * Top Operators By Revenue
             * @default []
             */
            top_operators_by_revenue: components["schemas"]["OperatorPerformance"][];
        };
        /**
         * UserDetailResponse
         * @description Detailed user response with stats
         */
        UserDetailResponse: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Id */
            company_id: string | null;
            /** Role */
            role: string;
            /** Permissions */
            permissions: string[];
            /** Permission Group Id */
            permission_group_id?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Is Suspended */
            is_suspended: boolean;
            /** Email Verified */
            email_verified: boolean;
            /** Language */
            language: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Total Calls
             * @default 0
             */
            total_calls: number | null;
            /**
             * Total Leads
             * @default 0
             */
            total_leads: number | null;
            /**
             * Total Deals
             * @default 0
             */
            total_deals: number | null;
            /**
             * Total Tasks
             * @default 0
             */
            total_tasks: number | null;
        };
        /**
         * UserInviteRequest
         * @description Admin invites operator via email
         */
        UserInviteRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Role
             * @description Role: company_admin or company_operator
             * @default company_operator
             */
            role: string;
            /**
             * Permissions
             * @description Custom permissions
             */
            permissions?: string[] | null;
            /**
             * Permission Group Id
             * @description Permission group to assign
             */
            permission_group_id?: string | null;
        };
        /**
         * UserListResponse
         * @description Paginated user list
         */
        UserListResponse: {
            /** Users */
            users: components["schemas"]["UserResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * UserResponse
         * @description User response
         */
        UserResponse: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Company Id */
            company_id: string | null;
            /** Role */
            role: string;
            /** Permissions */
            permissions: string[];
            /** Permission Group Id */
            permission_group_id?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Is Suspended */
            is_suspended: boolean;
            /** Email Verified */
            email_verified: boolean;
            /** Language */
            language: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserUpdateRequest
         * @description Update user information
         */
        UserUpdateRequest: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Suspended */
            is_suspended?: boolean | null;
            /** Role */
            role?: string | null;
            /** Permissions */
            permissions?: string[] | null;
            /**
             * Permission Group Id
             * @description Permission group to assign
             */
            permission_group_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_owner_api_v1_owner_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_owner_api_v1_owner_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerResponse"];
                };
            };
        };
    };
    reset_password_api_v1_owner_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_v1_owner_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_password_api_v1_owner_auth_set_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerWithCredentials"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies_api_v1_owner_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"][];
                };
            };
        };
    };
    create_company_api_v1_owner_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_admin_api_v1_owner_companies__company_id__invite_admin_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteAdminRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_v1_owner_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_company_api_v1_owner_companies__company_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_company_api_v1_owner_companies__company_id__delete: {
        parameters: {
            query?: {
                hard?: boolean;
            };
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_company_api_v1_owner_companies__company_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_company_api_v1_owner_companies__company_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contracts_api_v1_owner_contracts_get: {
        parameters: {
            query?: {
                company_id?: string | null;
                status?: components["schemas"]["ContractStatusEnum"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contract_api_v1_owner_contracts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contract_api_v1_owner_contracts__contract_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contract_api_v1_owner_contracts__contract_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renew_contract_api_v1_owner_contracts__contract_id__renew_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractRenewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_contract_api_v1_owner_contracts__contract_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contract_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_platform_analytics_api_v1_owner_analytics_platform_get: {
        parameters: {
            query?: {
                /** @description today, week, month, year */
                period?: string;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAnalytics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_owner_dashboard_api_v1_owner_analytics_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerDashboard"];
                };
            };
        };
    };
    clear_owner_cache_api_v1_owner_analytics_cache_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_permissions_api_v1_owner_permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
